import { ArrowLeft, ArrowRight, LoaderCircle } from 'lucide-react'
import { useTranslation } from 'react-i18next'
import type { ImportMapping, ImportPreview } from '../../api/client'
import { Messages } from './ImportMessages'

const semanticFields = ['timestamp', 'latitude', 'longitude', 'sog', 'course', 'heading'] as const
const speedUnits = ['kn', 'km/h', 'mph', 'm/s']
type Props = { preview: ImportPreview; mapping: ImportMapping; needsUnitConfirmation: boolean; busy: boolean; onSemanticField: (filename: string, column: string, semantic: string) => void; onUnit: (filename: string, column: string, unit: string) => void; onBack: () => void; onSave: () => void }
export function MappingStep({ preview, mapping, needsUnitConfirmation, busy, onSemanticField, onUnit, onBack, onSave }: Props) {
  const { t } = useTranslation()
  return <><div className="import-stage-heading"><h2>{t('import.stageMap')}</h2><p>{t('import.mapDescription')}</p></div>{preview.files.map((file) => <article className="import-mapping-card" key={file.filename}><h3>{file.filename}</h3><div className="import-mapping-grid"><span>{t('import.sourceColumn')}</span><span>{t('import.field')}</span><span>{t('import.sourceUnit')}</span>{file.columns.map((column) => <div className="import-mapping-row" key={column.source_column}><strong>{column.source_column}</strong><select aria-label={`${column.source_column} ${t('import.field')}`} value={mapping[file.filename]?.semantic_fields[column.source_column] ?? ''} onChange={(event) => onSemanticField(file.filename, column.source_column, event.target.value)}><option value="">{t('import.optionalMetric')}</option>{semanticFields.map((value) => <option key={value} value={value}>{t(`import.${value === 'sog' ? 'speed' : value}`)}</option>)}</select>{column.requires_unit_mapping ? <select aria-label={`${column.source_column} ${t('import.sourceUnit')}`} className={!mapping[file.filename]?.unit_overrides[column.source_column] ? 'is-required' : ''} value={mapping[file.filename]?.unit_overrides[column.source_column] ?? ''} onChange={(event) => onUnit(file.filename, column.source_column, event.target.value)}><option value="">{t('import.selectUnit')}</option>{speedUnits.map((unit) => <option key={unit} value={unit}>{unit}</option>)}</select> : <span>{column.detected_unit ?? t('import.notApplicable')}</span>}</div>)}</div></article>)}{needsUnitConfirmation ? <Messages heading={t('import.actionRequired')} messages={[t('import.unitRequired')]} tone="error" /> : null}<div className="import-stage-actions"><button type="button" className="import-secondary" onClick={onBack}><ArrowLeft size={16} />{t('import.back')}</button><button type="button" className="import-primary" onClick={onSave} disabled={busy || needsUnitConfirmation}>{busy ? <LoaderCircle className="is-spinning" size={16} /> : null}{t('import.validateImport')} <ArrowRight size={16} /></button></div></>
}
