import { ArrowLeft, Check, LoaderCircle } from 'lucide-react'
import { useTranslation } from 'react-i18next'
import type { ImportProgress, ImportValidation } from '../../api/client'

type Props = { validation: ImportValidation; imo: string; name: string; replacing: boolean; replaceConfirmed: boolean; busy: boolean; committing: boolean; progress: ImportProgress | null; onImoChange: (imo: string) => void; onNameChange: (name: string) => void; onReplaceConfirmedChange: (checked: boolean) => void; onBack: () => void; onCommit: () => void }
export function ReviewStep({ validation, imo, name, replacing, replaceConfirmed, busy, committing, progress, onImoChange, onNameChange, onReplaceConfirmedChange, onBack, onCommit }: Props) {
  const { t } = useTranslation()
  const progressPercent = progress?.enrichment_days_total ? (progress.enrichment_days_completed / progress.enrichment_days_total) * 100 : 0
  return <><div className="import-stage-heading"><h2>{t('import.stageReview')}</h2><p>{t('import.reviewDescription')}</p></div><section className="import-review"><label>IMO<input value={imo} onChange={(event) => onImoChange(event.target.value)} placeholder="IMO1234567" autoComplete="off" /></label><label>{t('import.vesselName')} <small>{t('import.optional')}</small><input value={name} onChange={(event) => onNameChange(event.target.value)} placeholder={t('import.vesselName')} autoComplete="off" /></label></section>{replacing ? <label className="import-replace-confirmation"><input type="checkbox" checked={replaceConfirmed} onChange={(event) => onReplaceConfirmedChange(event.target.checked)} />{t('import.replaceConfirm')}</label> : null}<section className="import-review-summary"><div><span>{t('import.validatedRows')}</span><strong>{validation.rows_accepted.toLocaleString()}</strong></div><div><span>{t('import.mode')}</span><strong>{replacing ? t('import.replaceMode') : t('import.createMode')}</strong></div><div><span>{t('import.estimatedMetrics')}</span><strong>{validation.estimated_metrics.join(', ')}</strong></div></section>{committing && progress ? <section className="enrichment-progress" aria-live="polite"><div><span>{t('enrichment.weatherData')}</span><strong>{progress.imo}</strong></div><div className="enrichment-progress-status"><span>{t('enrichment.fetching')}</span><span>{progress.enrichment_days_total ? t('enrichment.daysComplete', { completed: progress.enrichment_days_completed, total: progress.enrichment_days_total }) : t('enrichment.preparing')}</span></div><div className="enrichment-progress-track" role="progressbar" aria-label={t('enrichment.weatherData')} aria-valuemin={0} aria-valuemax={progress.enrichment_days_total || undefined} aria-valuenow={progress.enrichment_days_completed}><span style={{ width: `${progressPercent}%` }} /></div></section> : null}<div className="import-stage-actions"><button type="button" className="import-secondary" onClick={onBack} disabled={busy}><ArrowLeft size={16} />{t('import.back')}</button><button type="button" className="import-primary" onClick={onCommit} disabled={busy || !imo.trim() || (replacing && !replaceConfirmed)}>{busy ? <LoaderCircle className="is-spinning" size={16} /> : null}{replacing ? t('import.replaceImport') : t('import.commitImport')} <Check size={16} /></button></div></>
}
