import { ArrowLeft, ArrowRight, LoaderCircle } from 'lucide-react'
import { useTranslation } from 'react-i18next'
import type { ImportValidation } from '../../api/client'
import { IssueList, Messages } from './ImportMessages'

export function ValidationStep({ validation, busy, onBack, onValidate }: { validation: ImportValidation | null; busy: boolean; onBack: () => void; onValidate: () => void }) {
  const { t } = useTranslation()
  const hasErrors = validation?.issues.some((issue) => issue.severity === 'error') ?? false
  return <><div className="import-stage-heading"><h2>{t('import.stageValidate')}</h2><p>{t('import.validateDescription')}</p></div>{validation ? <><IssueList heading={t('import.validationErrors')} issues={validation.issues.filter((issue) => issue.severity === 'error')} tone="error" /><IssueList heading={t('import.validationWarnings')} issues={validation.issues.filter((issue) => issue.severity === 'warning')} tone="warning" /><IssueList heading={t('import.validationInformation')} issues={validation.issues.filter((issue) => issue.severity === 'information')} tone="info" /><section className="import-validation-summary"><div><strong>{validation.rows_accepted.toLocaleString()}</strong><span>{t('import.acceptedRows')}</span></div><div><strong>{validation.rows_rejected.toLocaleString()}</strong><span>{t('import.rejectedRows')}</span></div><div><strong>{validation.estimated_metrics.join(', ')}</strong><span>{t('import.estimatedAfterImport')}</span></div></section>{hasErrors ? <p className="import-help">{t('import.correctMapping')}</p> : <Messages heading={t('import.readyForReview')} messages={[t('import.validationPassed')]} tone="info" />}</> : <div className="import-empty-validation"><LoaderCircle className="is-spinning" size={22} /><p>{t('import.validationNotRun')}</p></div>}<div className="import-stage-actions"><button type="button" className="import-secondary" onClick={onBack}><ArrowLeft size={16} />{t('import.backToMapping')}</button><button type="button" className="import-primary" onClick={onValidate} disabled={busy}>{busy ? <LoaderCircle className="is-spinning" size={16} /> : null}{hasErrors ? t('import.validateAgain') : validation ? t('import.continueReview') : t('import.runValidation')} <ArrowRight size={16} /></button></div></>
}
