import { useState } from 'react'
import type { Metric, TelemetryRecord } from '../api/client'

type TelemetryFramesProps = { imo: string; records: TelemetryRecord[]; metrics: Metric[]; selectedTimestamp: string; onFrameSelect: (timestamp: string) => void }
const columns: Array<{ key: keyof TelemetryRecord; label: string; metricKey?: string }> = [{ key: 'timestamp', label: 'Timestamp' }, { key: 'latitude_deg', label: 'Latitude' }, { key: 'longitude_deg', label: 'Longitude' }, { key: 'sog_knots', label: 'SOG', metricKey: 'sog' }, { key: 'heading_deg', label: 'Heading', metricKey: 'heading' }, { key: 'course_deg', label: 'Course', metricKey: 'course' }, { key: 'estimated_rpm', label: 'RPM', metricKey: 'estimated_rpm' }, { key: 'estimated_fuel_tpd', label: 'Fuel', metricKey: 'estimated_fuel_tpd' }]
function format(value: unknown) { return typeof value === 'number' ? value.toFixed(2) : typeof value === 'string' ? value : '-' }

export function TelemetryFrames({ imo, records, metrics, selectedTimestamp, onFrameSelect }: TelemetryFramesProps) {
  const [metricKey, setMetricKey] = useState('')
  const metric = metrics.find((item) => item.key === metricKey)
  const selected = records.find((record) => record.timestamp === selectedTimestamp) ?? records.at(-1)
  return <section className="telemetry-frames" aria-label="Telemetry frames"><div className="frames-heading"><div><p className="eyebrow">03</p><h2>Telemetry frames</h2></div><span>{imo || 'No vessel selected'} · {records.length.toLocaleString()} frames</span></div>{selected ? <div className="selected-frame"><span>{new Date(selected.timestamp).toLocaleString()}</span><strong>RPM {selected.estimated_rpm.toFixed(1)}</strong><strong>HDG {selected.heading_deg?.toFixed(1) ?? '-'}</strong><strong>LAT {selected.latitude_deg.toFixed(4)}</strong><strong>LON {selected.longitude_deg.toFixed(4)}</strong></div> : null}{metric ? <div className="metric-popover" role="dialog" aria-label={`${metric.label} metric details`}><button type="button" aria-label="Close metric details" onClick={() => setMetricKey('')}>Close</button><strong>{metric.label}</strong><span>{metric.origin} · {metric.unit || 'unitless'}</span><span>{metric.source_column ? `Imported from ${metric.source_column}` : metric.formula ?? 'Derived from normalized telemetry.'}</span>{metric.warning ? <span>{metric.warning}</span> : null}</div> : null}<div className="frame-table-wrap"><table><thead><tr>{columns.map((column) => <th key={column.key}><button type="button" onClick={() => column.metricKey && setMetricKey(column.metricKey)}>{column.label}</button></th>)}</tr></thead><tbody>{records.slice(-240).reverse().map((record) => { const incomplete = record.missing_fields.length > 0; return <tr key={record.timestamp} className={`${record.timestamp === selected?.timestamp ? 'is-current ' : ''}${incomplete ? 'is-incomplete' : ''}`} onClick={() => onFrameSelect(record.timestamp)}>{columns.map((column) => { const missing = column.metricKey && record.missing_fields.includes(column.metricKey); return <td key={column.key} className={missing ? 'is-missing' : ''}>{missing ? 'Missing' : format(record[column.key])}</td> })}</tr> })}</tbody></table></div></section>
}
