import { useEffect, useRef, useState } from 'react'
import type { TelemetryRecord } from '../api/client'
import { vesselColor } from '../vesselColors'
import './telemetryFrames.css'

type VesselTelemetry = { imo: string; records: TelemetryRecord[] }
type Props = { vessels: VesselTelemetry[]; focusedImo: string; selectedTimestamp: string; onFrameSelect: (timestamp: string) => void; routeStart: string; routeEnd: string; onRouteStartChange: (date: string) => void; onRouteEndChange: (date: string) => void; goToTelemetryRequest: number }
type Day = { imo: string; date: string; records: TelemetryRecord[]; distance: number; averageSpeed: number }
const frameColumns: Array<{ key: keyof TelemetryRecord; label: string }> = [{ key: 'timestamp', label: 'Timestamp' }, { key: 'latitude_deg', label: 'Latitude' }, { key: 'longitude_deg', label: 'Longitude' }, { key: 'sog_knots', label: 'SOG' }, { key: 'heading_deg', label: 'Heading' }, { key: 'course_deg', label: 'Course' }]
const format = (value: unknown) => typeof value === 'number' ? value.toFixed(2) : typeof value === 'string' ? value : '-'
function nauticalMiles(a: TelemetryRecord, b: TelemetryRecord) { const lat = (b.latitude_deg - a.latitude_deg) * Math.PI / 180; const lon = ((b.longitude_deg - a.longitude_deg + 540) % 360 - 180) * Math.PI / 180; const h = Math.sin(lat / 2) ** 2 + Math.cos(a.latitude_deg * Math.PI / 180) * Math.cos(b.latitude_deg * Math.PI / 180) * Math.sin(lon / 2) ** 2; return 3440.1 * 2 * Math.atan2(Math.sqrt(h), Math.sqrt(1 - h)) }
function summarize(vessels: VesselTelemetry[]): Day[] { return vessels.flatMap(({ imo, records }) => { const groups = new Map<string, TelemetryRecord[]>(); records.forEach((record) => { const date = record.timestamp.slice(0, 10); groups.set(date, [...(groups.get(date) ?? []), record]) }); return [...groups.entries()].map(([date, day]) => ({ imo, date, records: day, distance: day.slice(1).reduce((total, record, index) => total + nauticalMiles(day[index], record), 0), averageSpeed: day.reduce((total, record) => total + record.sog_knots, 0) / day.length })) }) }

export function TelemetryFrames({ vessels = [], focusedImo, selectedTimestamp, onFrameSelect, routeStart, routeEnd, onRouteStartChange, onRouteEndChange, goToTelemetryRequest }: Props) {
  const [page, setPage] = useState(0); const [expanded, setExpanded] = useState<string | null>(null); const selectedRowRef = useRef<HTMLTableRowElement>(null)
  const focusedRecords = vessels.find((vessel) => vessel.imo === focusedImo)?.records ?? []; const selected = focusedRecords.find((record) => record.timestamp === selectedTimestamp) ?? focusedRecords.at(-1); const selectedDay = selected?.timestamp.slice(0, 10)
  const summaries = summarize(vessels); const dates = [...new Set(summaries.map((day) => day.date))].sort(); const pageDates = dates.slice(Math.max(0, dates.length - (page + 1) * 30), dates.length - page * 30).reverse(); const days = summaries.filter((day) => pageDates.includes(day.date)).sort((a, b) => b.date.localeCompare(a.date) || a.imo.localeCompare(b.imo))
  useEffect(() => { if (goToTelemetryRequest && selectedDay) setExpanded(`${focusedImo}:${selectedDay}`) }, [goToTelemetryRequest, focusedImo, selectedDay])
  useEffect(() => { if (goToTelemetryRequest) selectedRowRef.current?.scrollIntoView({ behavior: 'smooth', block: 'center' }) }, [goToTelemetryRequest, expanded])
  return <section className="telemetry-frames" aria-label="Telemetry frames"><div className="frames-heading"><div><p className="eyebrow">04</p><h2>Daily navigation summary</h2></div><span>{vessels.length} vessel{vessels.length === 1 ? '' : 's'} · {summaries.length} daily summaries</span></div><details className="route-filters"><summary>Filtres de trajectoire / Route filters</summary><div><label>Date de debut / Start <input type="date" value={routeStart} onChange={(event) => onRouteStartChange(event.target.value)} /></label><label>Date de fin / End <input type="date" value={routeEnd} onChange={(event) => onRouteEndChange(event.target.value)} /></label></div></details><div className="frame-pagination"><button type="button" disabled={dates.length <= (page + 1) * 30} onClick={() => setPage((value) => value + 1)}>Older 30 days</button><span>{pageDates.at(-1)} to {pageDates[0]}</span><button type="button" disabled={!page} onClick={() => setPage((value) => Math.max(0, value - 1))}>Newer 30 days</button></div><div className="frame-table-wrap"><table><thead><tr><th>Vessel</th><th>Date</th><th>Frames</th><th>First position</th><th>Last position</th><th>Distance</th><th>Avg SOG</th></tr></thead><tbody>{days.map((day) => { const key = `${day.imo}:${day.date}`; const first = day.records[0]; const last = day.records.at(-1)!; const focusedDay = day.imo === focusedImo && day.date === selectedDay; return <><tr ref={focusedDay ? selectedRowRef : undefined} key={key} className={`day-summary ${focusedDay ? 'is-current-day' : ''}`} onClick={() => setExpanded((value) => value === key ? null : key)}><td><span className="vessel-table-dot" style={{ background: vesselColor(day.imo) }} />{day.imo}</td><td>{day.date}</td><td>{day.records.length}</td><td>{first.latitude_deg.toFixed(3)}, {first.longitude_deg.toFixed(3)}</td><td>{last.latitude_deg.toFixed(3)}, {last.longitude_deg.toFixed(3)}</td><td>{day.distance.toFixed(1)} nm</td><td>{day.averageSpeed.toFixed(1)} kn</td></tr>{expanded === key ? <tr key={`${key}-frames`} className="day-frames"><td colSpan={7}><table><thead><tr>{frameColumns.map((column) => <th key={column.key}>{column.label}</th>)}</tr></thead><tbody>{day.records.map((record) => <tr key={record.timestamp} onClick={() => day.imo === focusedImo && onFrameSelect(record.timestamp)}>{frameColumns.map((column) => <td key={column.key}>{format(record[column.key])}</td>)}</tr>)}</tbody></table></td></tr> : null}</> })}</tbody></table></div></section>
}
